### ISSUE TITLE
Add system76 PPA as alternative source for Chromium.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/doc-user-guide#13]
I recently noticed that the system76 team has Chromium to be installed as PPA, maybe it could be added as an additional source.

https://launchpad.net/~system76/+archive/ubuntu/pop/

> sudo add-apt-repository ppa:system76/pop
> sudo apt-update
> sudo apt install chromium

**Comment by smurphos** [comment]
Hi @haggen88,

I don't think using the pop PPA is a good idea - 

1) it ships a number of other packages that could cause issues on a non POP system - note the disclaimer on the PPA

> WARNING: This PPA is for Pop!_OS, and it may cause breakage on other Ubuntu-based OS's. Use of this repository on non-Pop_OS installations is at your own risk!

2) although at time of writing the chromium version is reasonably up to date, until a couple of weeks ago the build was several months old - I wouldn't be confident that the POP version is going to get security updates in a timely manner going forward.

**Comment by haggen88** [comment]
There is another source available:    https://launchpad.net/~ts.sch.gr/+archive/ubuntu/chromium-browser
regards
