### ISSUE TITLE
Can't find downloadable version

### ISSUE THREAD

**Issue by MarjaE2** [linuxmint/doc-user-guide#26]
Hi,

If users can't use readthedocs, because it triggers migraines, or want to read the documentation elsewhere, on an e-reader, etc, a downloadable version would be very helpful. If it does exist, it's hard to find on readthedocs because it's readthedocs.

**Comment by MarjaE2** [comment]
The page here says each section "is available in English, in HTML, PDF and ePub."

https://www.linuxmint.com/documentation.php

They aren't.

**Comment by mtwebster** [comment]
Probably not as discoverable as it could be, but click on "Read the docs" at the bottom of the sidebar:
![image](https://github.com/linuxmint/doc-user-guide/assets/262776/e8eca225-f206-44ec-ad6f-14435896aa32)
