### ISSUE TITLE
Snap section is largely composed of unhelpful fear mongering

### ISSUE THREAD

**Issue by flying-frigate-technologies** [linuxmint/doc-user-guide#29]
The section on Snap is composed almost entirely of unhelpful fear-mongering that seeks to pursue a vendetta against Canonical with dubious leaps of logic (e.g. because snapd isn't designed to work with other stores, snaps are all effectively proprietary).

I shan't pretend to understand why some people in the Linux Mint community choose to use a supposedly 'user-friendly' distro to try to force a certain set of philosophical ideas as opposed to try to make it easy for new users to switch to Linux, but this is really an egregious case of using the documents as a blogging platform to fear monger about organisations they dislike instead of providing useful information.

Heck, what do I care, it's junk like this that means I use Windows instead of Linux, but just give this a thought. j

**Comment by leigh123linux** [comment]
This is my opinion as a Fedora dev.

Maybe you should aim your spite at Canonical instead for going their own way.
They could have supported Flatpak instead, this would have been universal support across all distro's.
Instead they chose to go with their own solution, these rarely last long, remember Mir, Unity and the stupid gnome hacks they had to reverse?.

**Comment by flying-frigate-technologies** [comment]
And maybe whoever created Flatpak should just have stuck with AppImage, but hey, this is Linux, it's not like the existence of .SH and .RUN prevented the development of .DEBs and APT (and all the other alternatives different distributions have) - having about 12 ways to install software which work at random across different distros is sort of how you seem to do things.

All I am here to say is that subjecting new Linux users to a vendetta against Canonical is unhelpful to encouraging people to try Linux on the desktop. Perhaps people should consider just giving helpful instructions instead in the documentation, or at least placing them above whatever rants they would like to have about a "Backdoor via APT".

For what its worth, I was actually going to give Linux through Linux Mint another go, but this documentation (and Linus Tech Tips experience) has made me realise that Linux is still made by a bunch of programmers with no design sense and no interest in making a usable operating system ahead of persuing a bunch of philosophical vendettas that are utterly irrelevant to the average user.

**Comment by flying-frigate-technologies** [comment]
If Linux Mint gave two hoots about usability it would support both out of the box (along with media codecs, but that's another issue). That's not what I am asking for, all I am asking for is that in documentation **_useful instructions to new users are put ahead of fearmongering._**

Maybe Canonical should get some of my ire, though as I say, if I were going to start criticising people who built random extra ways of installing stuff I would have to start with the makers of APT, RPM, and PacMan. But there is something simple people can do right now to make Linux a better experience for new users which is burying the hatchet and making documentation that actually informs people rather than shouts at them.

**Comment by leigh123linux** [comment]
> If Linux Mint gave two hoots about usability it would support both out of the box (along with media codecs, but that's another issue). That's not what I am asking for, all I am asking for is that in documentation **_useful instructions to new users are put ahead of fearmongering._**
> 
> Maybe Canonical should get some of my ire, though as I say, if I were going to start criticising people who built random extra ways of installing stuff I would have to start with the makers of APT, RPM, and PacMan. But there is something simple people can do right now to make Linux a better experience for new users which is burying the hatchet and making documentation that actually informs people rather than shouts at them.

RPM existed before APT and pacman

https://en.wikipedia.org/wiki/RPM_Package_Manager
https://en.wikipedia.org/wiki/APT_(software)
https://en.wikipedia.org/wiki/Arch_Linux


Personally I think Mint's criticism of snap is fair for the following reasons.

1. Why should Canonical have sole control on the app store
2.  What gives them the right to replace apt app's like firefox or chromium  without user permission.

https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html#criticism

They also give the user a guide to enable snap if they wish to.

https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html#how-to-install-the-snap-store-in-linux-mint-20


You haven't managed to convince me your not a Canonical troll.


FTR I don't use flatpak, snap or appimage.

**Comment by flying-frigate-technologies** [comment]
> You haven't managed to convince me your not a Canonical troll.

I hope this will convince you: I do not like Ubuntu. I do not use Ubuntu. I do not like or use any variety of Linux. I use Windows 10. I am happy with that, I just have an old computer that doesn't support Windows 10 that I am trying to get running again, and I am trying to find a variety of Linux that is maintained by people who put ease of use first.

**Comment by flying-frigate-technologies** [comment]
> RPM existed before APT and pacman
> 
> https://en.wikipedia.org/wiki/RPM_Package_Manager 
>https://en.wikipedia.org/wiki/APT_(software) 
>https://en.wikipedia.org/wiki/Arch_Linux

Interesting, but the point still stands - if I am to criticise Canonical for duplicating flatpak, then I would have to criticise the makers or APT and pacman for duplicating RPM.

For the sake of clarity, I think supporting both snap and flatpak out of the box is a good proxy for a distro that puts user-friendliness first. By contrast, I think putting a 1-page polemic on why snap is a menace to humanity at the start of installation documentation is a good proxy for a distro that puts vendettas first.

However, as I think this documentation makes clear, Linux Mint is the later. I think I will either give up with my search or move on - I know not which.

Best wishes and have a good day.

**Comment by leigh123linux** [comment]
> > RPM existed before APT and pacman
> > https://en.wikipedia.org/wiki/RPM_Package_Manager
> > https://en.wikipedia.org/wiki/APT_(software)
> > https://en.wikipedia.org/wiki/Arch_Linux
> 
> Interesting, but the point still stands - if I am to criticise Canonical for duplicating flatpak, then I would have to criticise the makers or APT and pacman for duplicating RPM.
> 
> For the sake of clarity, I think supporting both snap and flatpak out of the box is a good proxy for a distro that puts user-friendliness first. By contrast, I think putting a 1-page polemic on why snap is a menace to humanity at the start of installation documentation is a good proxy for a distro that puts vendettas first.
> 
> However, as I think this documentation makes clear, Linux Mint is the later. I think I will either give up with my search or move on - I know not which.
> 
> Best wishes and have a good day.

Maybe try ubuntu cinnamon

https://sourceforge.net/projects/ubuntu-cinnamon-remix/files/

**Comment by leigh123linux** [comment]
@flying-frigate-technologies  Here's another reason to avoid snap store.

https://www.phoronix.com/news/Snap-Store-Malicious-Apps

**Comment by Secret-chest** [comment]
First, Flatpak is not duplicating AppImage, as AppImage is not a package manager, just a format like Windows EXE.
