### ISSUE TITLE
[BUG] Update to 22: I DON'T WANT SNAPSHOT

### ISSUE THREAD

**Issue by gander** [linuxmint/doc-user-guide#37]
I'm upgrading to 22 and the script is stuck on snapshots. I have a snapshot taken as root, but no, a regular snapshot must be taken or it won't go any further. Whose genius came up with this brilliant idea? Very bad and very frustrating idea. That's not how it's done. If I want to upgrade without a snapshot, or have another solution, I'll proceed at my own risk, and I won't see the same idiotic message over and over again.

**Comment by Jeremy7701** [comment]
Go to preferences and say you don't want a snapshot.
Obviously, this seems wrong since it could just ask - "have you taken a snapshot today?"
